version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - microservices-network

  accountservice.api:
    build:
      context: ./AccountService.Api
      dockerfile: Dockerfile
    container_name: accountservice.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - microservices-network

  clientservice.api:
    build:
      context: ./ClientService.Api
      dockerfile: Dockerfile
    container_name: clientservice.api
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge